### ISSUE TITLE
Renaming Labels Breaks Media Links

### ISSUE THREAD

**Issue by stanparker** [PronghornDigital/Montana-News-Archive#100]
When labels are renamed, paths to video and photos break.

**Comment by DavidSouther** [comment]
We have a method that's supposed to do exactly this - https://github.com/PronghornDigital/Montana-News-Archive/blob/master/src/api/record/record.ts#L115

We need to add tests for it explicitly.

**Comment by DavidSouther** [comment]
Ah, we do do that, and it works. We don't update the record's data, though.
