### ISSUE TITLE
Editing Dates of Records Doesn't Save

### ISSUE THREAD

**Issue by stanparker** [PronghornDigital/Montana-News-Archive#101]
Changes made to dates don't persist after page reloads.

**Comment by DavidSouther** [comment]
1. Click "Edit"
2. Change the start or end date of a Tape
3. Click "Done"
  a. See the "Record Saved" toast
4. Reload the page

Expect: The record has the new date.

Actual: The record has the original date.

**Comment by stanparker** [comment]
Closed with #105
