### ISSUE TITLE
Need a way to edit stories

### ISSUE THREAD

**Issue by stanparker** [PronghornDigital/Montana-News-Archive#40]
Need to be able to edit stories.

**Comment by DavidSouther** [comment]
Would you rather have:
1) click to edit cell
2) button on far right to edit row (per row)
3) Button in header to edit all rows

**Comment by stanparker** [comment]
I would say I'm evenly split on 1 & 2, so whichever is easiest.

**Comment by DavidSouther** [comment]
Closed in #93
