### ISSUE TITLE
Change "Associate" to "Add Video"

### ISSUE THREAD

**Issue by stanparker** [PronghornDigital/Montana-News-Archive#51]
Or "link video"

**Comment by DavidSouther** [comment]
@stanparker this should just be a copy change at https://github.com/PronghornDigital/Montana-News-Archive/blob/master/src/client/mtna/record/associate/associate-component.ts#L84

**Comment by DavidSouther** [comment]
PR #81

**Comment by DavidSouther** [comment]
Closed by #81
