### ISSUE TITLE
Can't Associate Video on the NAS

### ISSUE THREAD

**Issue by stanparker** [PronghornDigital/Montana-News-Archive#58]
When trying to associate video, the server gave this error:

`Error: EXDEV: cross-device link not permitted, rename '/home/stanparker/Montana-News-Archive/incoming/Adam001.mp4 -> '/home/stanparker/Montana-News-Archive/data/adam_1/Adam001.mp4'`
`        at Error (native)`

The NAS was linked with the following method:

`mkdir incoming`

`sudo mount -t cifs //192.168.1.84/Incoming incoming`

**Comment by DavidSouther** [comment]
I think `incoming/` and `data/` will need to be on the same network mount.

**Comment by stanparker** [comment]
Video association now works!
