### ISSUE TITLE
Ability to Delete Records

### ISSUE THREAD

**Issue by stanparker** [PronghornDigital/Montana-News-Archive#59]
In case of duplicate entries or other situations where simply editing the record isn't a good solution.

**Comment by DavidSouther** [comment]
For delete - this is a hard delete, completely removing including associated media?

If so, the confirmation will read:

Are you sure you want to delete this tape? {{ if hasMedia }}That will permanently delete {{ videoCount }} videos and {{imageCount}} images.{{ endif }}

[No] [Yes]

**Comment by stanparker** [comment]
Hard delete, for the record yes.

As far as the data goes, could we move it to a trash folder? So in the data root folder you'd have
- data
- incoming
- trash

**Comment by DavidSouther** [comment]
Not in this PR. I'll add that as a note to #46.

**Comment by stanparker** [comment]
Okay, delete everything except the videos, which we will move back to the /incoming folder, renaming them to "<original name> + "Recovered at" + <timestamp>"

**Comment by DavidSouther** [comment]
Closed by #110
