### ISSUE TITLE
Videos Display Blank Player

### ISSUE THREAD

**Issue by stanparker** [PronghornDigital/Montana-News-Archive#67]
For stories with a video associated, a blank player shows up with no video source.

HTML example from page:

```
<div flex-md="50" ng-repeat="video in state.record.videos" class="ng-scope flex-md-50">
<video controls="controls">
<source type="video/mp4">
</video>
</div>

```

**Comment by DavidSouther** [comment]
Discussed on chat - videos must be correctly encoded `video/mp4`, full stop.
