### ISSUE TITLE
Allow duplicate slugs

### ISSUE THREAD

**Issue by stanparker** [PronghornDigital/Montana-News-Archive#70]

**Comment by DavidSouther** [comment]
We might want to reconsider this - if we allow associating a video directly with a slug, instead of a record, then the folder path generated again needs to be unique for the slug's video.

**Comment by stanparker** [comment]
Hmm.... you bring up a good point, and I don't know for sure the best way
to handle it on the backend. But I do know that it has to be allowed. A lot
of slugs, unfortunately, are just "City Council" or "Weather Window" and
the person entering the data shouldn't have to make decisions about how to
handle that as they're entering it.

Oh, here's a thought. What if we make the slug folder paths include the
date as well? ie 1985_06_03_city_council -- but then I guess that doesn't
really help us in the event that a tape index is missing dates for stories,
which happens.

**Comment by DavidSouther** [comment]
> 1985_06_03_city_council

It already does: 1985_06_03/city_council (EG you can have the same slug in different records).

**Comment by stanparker** [comment]
It does? I guess I don't understand what you're referring to there.

But anyway, here's an example For this tape:
[alex_1_36999756190925837](https://cloud.githubusercontent.com/assets/3110419/14060083/8f4fb9e0-f32e-11e5-957a-6a91286ffbfd.jpeg)

You can see that there are a couple different stories with the same slugs: "WX Window" appears several times. 

So what if the paths created for those slugs included the date as well to make them unique.  so in this example it would be
- alex_1/1995_02_02_wx_window
- alex_1/1995_02_05_wx_window
-alex_1/1995_02_06_wx_window
-etc

**Comment by DavidSouther** [comment]
Closed in #93
