### ISSUE TITLE
submit/return does not save a story record

### ISSUE THREAD

**Issue by JonathanPorta** [PronghornDigital/Montana-News-Archive#80]
The story creation form does not all you to submit by pressing enter/return. You have to tab all the way to the `+` button to save.

Also, `+`'s are for adding a new entry when no entry form exists. Not for saving the current form.

**Comment by DavidSouther** [comment]
NB: This should be done in such a way as to also close #91.

**Comment by DavidSouther** [comment]
Closed in #93
